spring:
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.mailgun.org
    username: admin@sandbox2a0b6386bd7b4294b28213fc49a39acc.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  email:
    url: "http://domain:8080"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "https://chirp.pl-coding.com"