spring:
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mailgun.org
    username: admin@sandbox2a0b6386bd7b4294b28213fc49a39acc.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"

logging:
  level:
    com.cso.chirp: DEBUG